package com.softray.internship.entities;


import lombok.Data;
import javax.persistence.*;
/*
    A PassengerEntity class representing the passenger entity in the database
    Attributes:
        -id : auto generated by java persistence package
        -firstName
        -lastName
        -passportID : must be unique
        -email
    PassengerEntity stored in passengers table, indexed by the passportID
 */
@Data
@Entity
@Table(
        name = "passengers",
        indexes = {
                @Index(name = "passport_id_index", columnList = "passport_id", unique = true )
        }
)
public class PassengerEntity {

    @Id
    @GeneratedValue
    private Long id;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "passport_id")
    private int passportID;

    @Column(name = "email")
    private String email;

    /*
        A getter metod to retrieve the id
        Auto getters and setters by lombok, but manual getter needed
     */
    public Long getId() {
        return id;
    }

    /*
        A method for the instance PassengerEntity to update itself.
        Used in the update endpoints in order to update the entity without updating its database id or passport id
     */
    public void updateMe (PassengerEntity newPassenger){
        if (!this.firstName.equals(newPassenger.firstName)){
            this.firstName= newPassenger.firstName;
        }
        if (!this.lastName.equals(newPassenger.lastName)){
            this.lastName= newPassenger.lastName;
        }
        if (!this.email.equals(newPassenger.email)){
            this.email= newPassenger.email;
        }
    }
}
